spring:
  profiles:
    active: swagger
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true

server:
  port: 8080
  address: 0.0.0.0

search:
  host: localhost
  port: 9200
  batchSize: 2000
  trackingTaskRequestInterval: PT30S
  product:
    indexName: product
    configFile: product-index-2.json
  recording:
    indexName: song-index-dev
    configFile: recording_index.json
  contact:
    indexName: contact-index-dev
    configFile: contact_index.json
  project:
    indexName: project-index-dev
    configFile: project_index.json
  internalUser:
    indexName: internal-user-index-dev
    configFile: internal_user_index.json
  group:
    indexName: group-index
    configFile: group_index.json
  work:
    indexName: work-index
    configFile: work_index.json
  company:
    indexName: company-index-dev
    configFile: company_index.json

